Update provision.yml

diff --git a/.github/workflows/provision.yml b/.github/workflows/provision.yml
--- a/.github/workflows/provision.yml
+++ b/.github/workflows/provision.yml
@@ -25,65 +25,66 @@ jobs:
           AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
           BACKEND_CONFIG: ${{ secrets.TF_BACKEND_CONFIG }}
           
-      - name: Set Env Variables
-        run: source ./azure/setup-env-variables.sh
+      
+# - name: Set Env Variables
+#         run: source ./azure/setup-env-variables.sh
         
-      - name: Terraform Format
-        run: terraform fmt -check
-      - name: Terraform Init
-        run: terraform init -backend-config=azurerm.tfbackend
-      - name: Terraform Validate
-        run: terraform validate
-      - name: Terraform Plan
-        id: plan
-        continue-on-error: true
-        run: |
-          terraform plan -input=false \
-            -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
-            -var "resource_group_location=${{ secrets.AZURE_LOCATION }}" \
-            -var "sso-jwk-uri=${{ secrets.OIDC_JWK_SET_URI }}" \
-            -var "sso-client-id=${{ secrets.OIDC_CLIENT_ID }}" \
-            -var "sso-client-secret=${{ secrets.OIDC_CLIENT_SECRET }}" \
-            -var "sso-issuer-uri=${{ secrets.OIDC_ISSUER_URI }}"
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-      - name: Terraform Apply
-        run: |
-          terraform apply -auto-approve -input=false \
-            -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
-            -var "resource_group_location=${{ secrets.AZURE_LOCATION }}" \
-            -var "sso-jwk-uri=${{ secrets.OIDC_JWK_SET_URI }}" \
-            -var "sso-client-id=${{ secrets.OIDC_CLIENT_ID }}" \
-            -var "sso-client-secret=${{ secrets.OIDC_CLIENT_SECRET }}" \
-            -var "sso-issuer-uri=${{ secrets.OIDC_ISSUER_URI }}"
-      - name: Set up Azure
-        uses: azure/login@v1
-        with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
-      - name: Set up Azure Spring Extension
-        run: az extension add --name spring
-      - name: Configure Spring Cloud Gateway
-        working-directory: azure/routes
-        run: ../../.github/scripts/gateway.sh
-        env:
-          RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
-          SPRING_APPS_SERVICE: ${{ env.SPRING_APPS_SERVICE }}
-          IDENTITY_SERVICE_APP: ${{ env.IDENTITY_SERVICE_APP }}
-          CART_SERVICE_APP: ${{ env.CART_SERVICE_APP }}
-          ORDER_SERVICE_APP: ${{ env.ORDER_SERVICE_APP }}
-          CATALOG_SERVICE_APP: ${{ env.CATALOG_SERVICE_APP }}
-          FRONTEND_APP: ${{ env.FRONTEND_APP }}
-      - name: Configure Identity Provider
-        run: ../.github/scripts/identity-provider.sh
-        env:
-          RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
-          SPRING_APPS_SERVICE: ${{ env.SPRING_APPS_SERVICE }}
-          IDENTITY_SERVICE_APP: ${{ env.IDENTITY_SERVICE_APP }}
-          CART_SERVICE_APP: ${{ env.CART_SERVICE_APP }}
-          ORDER_SERVICE_APP: ${{ env.ORDER_SERVICE_APP }}
-          CATALOG_SERVICE_APP: ${{ env.CATALOG_SERVICE_APP }}
-          FRONTEND_APP: ${{ env.FRONTEND_APP }}
-          CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID  }}
-          KEY_VAULT: ${{ env.KEY_VAULT }}
+#       - name: Terraform Format
+#         run: terraform fmt -check
+#       - name: Terraform Init
+#         run: terraform init -backend-config=azurerm.tfbackend
+#       - name: Terraform Validate
+#         run: terraform validate
+#       - name: Terraform Plan
+#         id: plan
+#         continue-on-error: true
+#         run: |
+#           terraform plan -input=false \
+#             -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
+#             -var "resource_group_location=${{ secrets.AZURE_LOCATION }}" \
+#             -var "sso-jwk-uri=${{ secrets.OIDC_JWK_SET_URI }}" \
+#             -var "sso-client-id=${{ secrets.OIDC_CLIENT_ID }}" \
+#             -var "sso-client-secret=${{ secrets.OIDC_CLIENT_SECRET }}" \
+#             -var "sso-issuer-uri=${{ secrets.OIDC_ISSUER_URI }}"
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
+#       - name: Terraform Apply
+#         run: |
+#           terraform apply -auto-approve -input=false \
+#             -var "project_name=${{ secrets.TF_PROJECT_NAME}}" \
+#             -var "resource_group_location=${{ secrets.AZURE_LOCATION }}" \
+#             -var "sso-jwk-uri=${{ secrets.OIDC_JWK_SET_URI }}" \
+#             -var "sso-client-id=${{ secrets.OIDC_CLIENT_ID }}" \
+#             -var "sso-client-secret=${{ secrets.OIDC_CLIENT_SECRET }}" \
+#             -var "sso-issuer-uri=${{ secrets.OIDC_ISSUER_URI }}"
+#       - name: Set up Azure
+#         uses: azure/login@v1
+#         with:
+#           creds: ${{ secrets.AZURE_CREDENTIALS }}
+#       - name: Set up Azure Spring Extension
+#         run: az extension add --name spring
+#       - name: Configure Spring Cloud Gateway
+#         working-directory: azure/routes
+#         run: ../../.github/scripts/gateway.sh
+#         env:
+#           RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
+#           SPRING_APPS_SERVICE: ${{ env.SPRING_APPS_SERVICE }}
+#           IDENTITY_SERVICE_APP: ${{ env.IDENTITY_SERVICE_APP }}
+#           CART_SERVICE_APP: ${{ env.CART_SERVICE_APP }}
+#           ORDER_SERVICE_APP: ${{ env.ORDER_SERVICE_APP }}
+#           CATALOG_SERVICE_APP: ${{ env.CATALOG_SERVICE_APP }}
+#           FRONTEND_APP: ${{ env.FRONTEND_APP }}
+#       - name: Configure Identity Provider
+#         run: ../.github/scripts/identity-provider.sh
+#         env:
+#           RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
+#           SPRING_APPS_SERVICE: ${{ env.SPRING_APPS_SERVICE }}
+#           IDENTITY_SERVICE_APP: ${{ env.IDENTITY_SERVICE_APP }}
+#           CART_SERVICE_APP: ${{ env.CART_SERVICE_APP }}
+#           ORDER_SERVICE_APP: ${{ env.ORDER_SERVICE_APP }}
+#           CATALOG_SERVICE_APP: ${{ env.CATALOG_SERVICE_APP }}
+#           FRONTEND_APP: ${{ env.FRONTEND_APP }}
+#           CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID  }}
+#           KEY_VAULT: ${{ env.KEY_VAULT }}
 
